version: '3'
services:
  redis:
    image: redis:latest
    ports:
     - 6379:6379
  database:
    image: postgres:11
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=antimateriel_db
