name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        node-version:
          - 12.x
    steps:         
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          
      - name: Install Dependencies
        run: yarn --prefer-offline
      
      - name: Run Lint
        run: yarn lint
        
      - name: Generate Types
        run: yarn codegen
              
      - name: Run Test
        run: yarn test:ci
        
      - name: Run Build
        run: yarn build
